### ISSUE TITLE
[Feature request] Docker continous deployment

### ISSUE THREAD

**Issue by loorisr** [logdyhq/logdy-core#79]
Hello

Thank for this amazing log analyzer!
What about continous deployment to build the docker image and upload it to Github or Docker hub ?

I can provide a PR if needed.

This is an example to build the Docker on each commit and upload the file to Docker hub.

````yaml
name: ci

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ github.repository }}:latest
````
